server:
  port: 8081

spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://localhost:3306/employees_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8888
